### ISSUE TITLE
no blender found

### ISSUE THREAD

**Issue by nortikin** [pskl/glitch3d#1]
```
$ glitch3d pillow.obj 
/var/lib/gems/2.3.0/gems/glitch3d-0.2.4.0/lib/glitch3d.rb:32:in `process_model': Make sure Blender is correctly installed (RuntimeError)
	from /var/lib/gems/2.3.0/gems/glitch3d-0.2.4.0/bin/glitch3d:17:in `<top (required)>'
	from /usr/local/bin/glitch3d:22:in `load'
	from /usr/local/bin/glitch3d:22:in `<main>'
```

**Comment by pskl** [comment]
Hello! You need to set the `BLENDER_EXECUTABLE_PATH` environment variable :) 
In bash for instance you'd need to do `export BLENDER_EXECUTABLE_PATH=/path/to/blender`.

This software cannot guess where Blender is installed on the host machine, sadly.

**Comment by nortikin** [comment]
hope you can grab it to sverchok.

**Comment by pskl** [comment]
What do you mean by grab it to sverchok? If you have Sverchok installed you can use glitch3d command line to do sverchok operations too.

**Comment by nortikin** [comment]
/var/lib/gems/2.3.0/gems/glitch3d-0.2.4.0/lib/glitch3d.rb:32:in `process_model': Make sure Blender is correctly installed (RuntimeError)
	from /var/lib/gems/2.3.0/gems/glitch3d-0.2.4.0/bin/glitch3d:17:in `<top (required)>'
	from /usr/local/bin/glitch3d:22:in `load'
	from /usr/local/bin/glitch3d:22:in `<main>'
